"""Ball feeders for table-tennis tasks."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

import torch

from mjlab.entity.entity import Entity
from mjlab.managers.scene_entity_config import SceneEntityCfg
from mjlab.tasks.ball_sports import (
  BallSportGeometry,
  BallSportGeometryCfg,
  resolve_ball_sport_geometry,
)

if TYPE_CHECKING:
  from mjlab.envs.manager_based_rl_env import ManagerBasedRlEnv


_DEFAULT_BALL_GEOM_CFG = SceneEntityCfg("ball", geom_names="pingpong_ball")
_DEFAULT_PLAY_AREA_CFG = SceneEntityCfg(
  "table", geom_names="pingpong_table_top_collision"
)
_DEFAULT_NET_CFG = SceneEntityCfg("table", geom_names="pingpong_net_collision")


@dataclass(frozen=True)
class TableTennisSample:
  """A candidate ball state generated by the feeder."""

  px: torch.Tensor
  py: torch.Tensor
  pz: torch.Tensor
  vx: torch.Tensor
  vy: torch.Tensor
  vz: torch.Tensor
  tx: torch.Tensor
  ty: torch.Tensor
  flight_t: torch.Tensor
  valid: torch.Tensor


@dataclass(kw_only=True)
class TrajectoryCheckCfg:
  """Configurable constraints for a generated first-bounce trajectory."""

  require_spawn_on_opponent_half: bool = True
  require_target_on_self_half: bool = True
  require_net_clearance: bool = True
  require_edge_crossing: bool = False
  require_second_bounce_outside_self_half: bool = False
  edge: str = "self_baseline"
  net_clearance: float = 0.06
  edge_clearance: float = 0.02
  second_bounce_outside_margin: float = 0.06
  flight_time_range: tuple[float, float] = (0.32, 0.75)
  vx_range: tuple[float, float] = (2.0, 8.0)
  vy_abs_max: float = 2.0


@dataclass(kw_only=True)
class TableTennisFeederCfg:
  """Generate scene-driven first-bounce table-tennis feeds."""

  ball_cfg: SceneEntityCfg = field(default_factory=lambda: SceneEntityCfg("ball"))
  ball_geom_cfg: SceneEntityCfg = field(
    default_factory=lambda: SceneEntityCfg("ball", geom_names="pingpong_ball")
  )
  play_area_cfg: SceneEntityCfg = field(
    default_factory=lambda: SceneEntityCfg(
      "table", geom_names="pingpong_table_top_collision"
    )
  )
  net_cfg: SceneEntityCfg = field(
    default_factory=lambda: SceneEntityCfg(
      "table", geom_names="pingpong_net_collision"
    )
  )
  bounce_surface_cfg: SceneEntityCfg | None = field(
    default_factory=lambda: SceneEntityCfg(
      "table", geom_names="pingpong_table_top_collision"
    )
  )
  landing_z_override: float | None = None
  self_side: str = "positive_x"

  spawn_x_range: tuple[float, float] = (0.20, 0.20)
  spawn_x_range_mode: str = "opponent_side_margin"
  spawn_y_range: tuple[float, float] = (-0.55, 0.55)
  spawn_y_range_mode: str = "field_fraction"
  spawn_z_offset: float = 0.002

  target_x_range: tuple[float, float] = (0.30, 0.12)
  target_x_range_mode: str = "self_baseline_margin"
  target_y_range: tuple[float, float] = (-0.13, 0.13)
  target_y_range_mode: str = "field_fraction"

  vz_std: float = 0.35
  vz_max: float = 3.4
  post_bounce_horizontal_scale: float = 0.94
  post_bounce_vertical_scale: float = 0.90
  gravity: float = 9.81
  max_resample_attempts: int = 64
  check: TrajectoryCheckCfg = field(default_factory=TrajectoryCheckCfg)

  def build(self, env: "ManagerBasedRlEnv") -> "TableTennisFeeder":
    return TableTennisFeeder(self, env)

  def geometry_cfg(self) -> BallSportGeometryCfg:
    return BallSportGeometryCfg(
      ball_geom_cfg=self.ball_geom_cfg,
      play_area_cfg=self.play_area_cfg,
      net_cfg=self.net_cfg,
      bounce_surface_cfg=self.bounce_surface_cfg,
      landing_z_override=self.landing_z_override,
      self_side=self.self_side,
    )


def _write_ball_state(
  env: "ManagerBasedRlEnv",
  ball: Entity,
  env_ids: torch.Tensor,
  pos_l: torch.Tensor,
  quat: torch.Tensor,
  lin_vel: torch.Tensor,
  ang_vel: torch.Tensor,
) -> None:
  origins = env.scene.env_origins[env_ids]
  pos_w = pos_l + origins
  pose = torch.cat([pos_w, quat], dim=-1)
  twist = torch.cat([lin_vel, ang_vel], dim=-1)
  ball.write_root_link_pose_to_sim(pose, env_ids=env_ids)
  ball.write_root_link_velocity_to_sim(twist, env_ids=env_ids)


def resolve_pingpong_ball_sport_geometry(
  env: "ManagerBasedRlEnv",
  cfg: TableTennisFeederCfg | None = None,
) -> BallSportGeometry:
  """Resolve the default pingpong field as generic ball-sport geometry."""
  geometry_cfg = (
    cfg.geometry_cfg()
    if cfg is not None
    else BallSportGeometryCfg(
      ball_geom_cfg=_DEFAULT_BALL_GEOM_CFG,
      play_area_cfg=_DEFAULT_PLAY_AREA_CFG,
      net_cfg=_DEFAULT_NET_CFG,
      bounce_surface_cfg=_DEFAULT_PLAY_AREA_CFG,
      self_side="positive_x",
    )
  )
  return resolve_ball_sport_geometry(env, geometry_cfg)


def _uniform_between(lo: torch.Tensor, hi: torch.Tensor) -> torch.Tensor:
  if torch.any(hi <= lo):
    raise ValueError("Invalid sampling range: upper bound must exceed lower bound.")
  return lo + torch.rand_like(lo) * (hi - lo)


def _resolve_x_range(
  geometry: BallSportGeometry, cfg_range: tuple[float, float], mode: str
) -> tuple[torch.Tensor, torch.Tensor]:
  lo_cfg, hi_cfg = cfg_range
  if mode == "absolute":
    lo = torch.full_like(geometry.net_x, lo_cfg)
    hi = torch.full_like(geometry.net_x, hi_cfg)
  elif mode == "opponent_side_margin":
    lo = geometry.opponent_bounds.x_min + lo_cfg
    hi = geometry.opponent_bounds.x_max - hi_cfg
  elif mode == "self_side_margin":
    lo = geometry.self_bounds.x_min + lo_cfg
    hi = geometry.self_bounds.x_max - hi_cfg
  elif mode in ("self_baseline_margin", "self_edge_margin"):
    lo = geometry.self_baseline_x - lo_cfg
    hi = geometry.self_baseline_x - hi_cfg
  else:
    raise ValueError(f"Unknown x-range mode {mode!r}.")
  return lo, hi


def _resolve_y_range(
  geometry: BallSportGeometry, cfg_range: tuple[float, float], mode: str
) -> tuple[torch.Tensor, torch.Tensor]:
  lo_cfg, hi_cfg = cfg_range
  if mode == "absolute":
    lo = torch.full_like(geometry.net_x, lo_cfg)
    hi = torch.full_like(geometry.net_x, hi_cfg)
  elif mode in ("field_fraction", "table_fraction"):
    lo = geometry.self_bounds.center_y + geometry.self_bounds.half_width * lo_cfg
    hi = geometry.self_bounds.center_y + geometry.self_bounds.half_width * hi_cfg
  else:
    raise ValueError(f"Unknown y-range mode {mode!r}.")
  return lo, hi


def _time_to_bounce_plane(
  z: torch.Tensor,
  vz: torch.Tensor,
  bounce_z: torch.Tensor,
  *,
  gravity: float,
  min_time: float = 1.0e-4,
) -> tuple[torch.Tensor, torch.Tensor]:
  a = torch.full_like(z, 0.5 * gravity)
  b = -vz
  c = bounce_z - z
  disc = b * b - 4.0 * a * c
  has_real_root = disc >= 0.0
  sqrt_disc = torch.sqrt(torch.clamp(disc, min=0.0))
  denom = 2.0 * a
  t0 = (-b - sqrt_disc) / denom
  t1 = (-b + sqrt_disc) / denom
  candidates = torch.stack((t0, t1), dim=-1)
  neg_inf = torch.full_like(candidates, -float("inf"))
  candidates = torch.where(candidates > min_time, candidates, neg_inf)
  t_hit = candidates.amax(dim=-1)
  valid = has_real_root & torch.isfinite(t_hit)
  return t_hit, valid


def _vz_min_for_net(
  px: torch.Tensor,
  tx: torch.Tensor,
  geometry: BallSportGeometry,
  *,
  gravity: float,
  net_clearance: float,
) -> tuple[torch.Tensor, torch.Tensor]:
  alpha = (geometry.net_x - px) / (tx - px).clamp_min(1.0e-6)
  denom = 2.0 * alpha * (1.0 - alpha)
  required_height = geometry.net_top_z + net_clearance - geometry.bounce_z
  numerator = gravity * torch.clamp(required_height, min=0.0)
  valid = (alpha > 0.0) & (alpha < 1.0) & (denom > 1.0e-6)
  vz_min = torch.sqrt(torch.clamp(numerator / denom.clamp_min(1.0e-6), min=0.0))
  return vz_min, valid


def _solve_first_bounce_velocity(
  px: torch.Tensor,
  py: torch.Tensor,
  pz: torch.Tensor,
  tx: torch.Tensor,
  ty: torch.Tensor,
  vz: torch.Tensor,
  geometry: BallSportGeometry,
  *,
  gravity: float,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
  flight_t, valid_t = _time_to_bounce_plane(
    pz, vz, geometry.bounce_z, gravity=gravity
  )
  vx = (tx - px) / flight_t.clamp_min(1.0e-6)
  vy = (ty - py) / flight_t.clamp_min(1.0e-6)
  return vx, vy, flight_t, valid_t


def _edge_x(geometry: BallSportGeometry, edge: str) -> torch.Tensor:
  if edge == "self_baseline":
    return geometry.self_baseline_x
  raise ValueError(f"Unknown trajectory edge {edge!r}.")


def check_candidate_trajectory(
  sample: TableTennisSample,
  geometry: BallSportGeometry,
  cfg: TableTennisFeederCfg,
) -> torch.Tensor:
  """Validate sampled feeds against generic ball-sport geometry constraints."""
  check = cfg.check
  valid = sample.valid.clone()
  bounce_z = geometry.bounce_z

  if check.require_spawn_on_opponent_half:
    valid &= (
      (sample.px >= geometry.opponent_bounds.x_min)
      & (sample.px <= geometry.opponent_bounds.x_max)
      & (sample.py >= geometry.opponent_bounds.y_min)
      & (sample.py <= geometry.opponent_bounds.y_max)
    )

  if check.require_target_on_self_half:
    valid &= (
      (sample.tx >= geometry.self_bounds.x_min)
      & (sample.tx <= geometry.self_bounds.x_max)
      & (sample.ty >= geometry.self_bounds.y_min)
      & (sample.ty <= geometry.self_bounds.y_max)
    )

  t_net = (geometry.net_x - sample.px) / sample.vx.clamp_min(1.0e-6)
  z_net = sample.pz + sample.vz * t_net - 0.5 * cfg.gravity * t_net * t_net
  if check.require_net_clearance:
    valid &= (
      (t_net > 0.0)
      & (t_net < sample.flight_t)
      & (z_net >= geometry.net_top_z + check.net_clearance)
    )

  valid &= (
    (sample.flight_t >= check.flight_time_range[0])
    & (sample.flight_t <= check.flight_time_range[1])
    & (sample.vx >= check.vx_range[0])
    & (sample.vx <= check.vx_range[1])
    & (sample.vy.abs() <= check.vy_abs_max)
    & (sample.vz > 0.0)
    & (sample.vz <= cfg.vz_max)
  )

  impact_vz = sample.vz - cfg.gravity * sample.flight_t
  post_vx = sample.vx * cfg.post_bounce_horizontal_scale
  post_vy = sample.vy * cfg.post_bounce_horizontal_scale
  post_vz = -impact_vz * cfg.post_bounce_vertical_scale
  edge_x = _edge_x(geometry, check.edge)
  edge_t = (edge_x - sample.tx) / post_vx.clamp_min(1.0e-6)
  edge_y = sample.ty + post_vy * edge_t
  edge_z = bounce_z + post_vz * edge_t - 0.5 * cfg.gravity * edge_t * edge_t

  if check.require_edge_crossing:
    valid &= (
      (impact_vz < 0.0)
      & (post_vx > 0.0)
      & (edge_t > 0.0)
      & (edge_y >= geometry.self_bounds.y_min)
      & (edge_y <= geometry.self_bounds.y_max)
      & (edge_z >= bounce_z + check.edge_clearance)
    )

  if check.require_second_bounce_outside_self_half:
    second_t = 2.0 * post_vz / cfg.gravity
    second_x = sample.tx + post_vx * second_t
    second_y = sample.ty + post_vy * second_t
    outside_x = second_x > geometry.self_bounds.x_max + check.second_bounce_outside_margin
    outside_y = (second_y < geometry.self_bounds.y_min) | (
      second_y > geometry.self_bounds.y_max
    )
    valid &= (second_t > 0.0) & (outside_x | outside_y)

  return valid


class TableTennisFeeder:
  """Runtime feeder with rejection sampling for scene-derived feeds."""

  def __init__(self, cfg: TableTennisFeederCfg, env: "ManagerBasedRlEnv") -> None:
    self.cfg = cfg
    self._env = env
    self._ball: Entity = env.scene[cfg.ball_cfg.name]

  @property
  def device(self) -> str | torch.device:
    return self._env.device

  def spawn(self, env_ids: torch.Tensor) -> None:
    if env_ids.numel() == 0:
      return
    dev = self.device
    n = env_ids.numel()
    px = torch.empty(n, device=dev)
    py = torch.empty(n, device=dev)
    pz = torch.empty(n, device=dev)
    vx = torch.empty(n, device=dev)
    vy = torch.empty(n, device=dev)
    vz = torch.empty(n, device=dev)

    remaining = torch.arange(n, device=dev)
    for _ in range(max(1, int(self.cfg.max_resample_attempts))):
      if remaining.numel() == 0:
        break
      sample = self._sample_candidate(env_ids[remaining])
      valid = sample.valid
      if torch.any(valid):
        write_ids = remaining[valid]
        px[write_ids] = sample.px[valid]
        py[write_ids] = sample.py[valid]
        pz[write_ids] = sample.pz[valid]
        vx[write_ids] = sample.vx[valid]
        vy[write_ids] = sample.vy[valid]
        vz[write_ids] = sample.vz[valid]
      remaining = remaining[~valid]

    if remaining.numel() > 0:
      fallback = self._fallback_candidate(env_ids[remaining])
      if not torch.all(fallback.valid):
        raise ValueError("Fallback table-tennis feed does not satisfy trajectory check.")
      px[remaining] = fallback.px
      py[remaining] = fallback.py
      pz[remaining] = fallback.pz
      vx[remaining] = fallback.vx
      vy[remaining] = fallback.vy
      vz[remaining] = fallback.vz

    pos = torch.stack((px, py, pz), dim=-1)
    lin = torch.stack((vx, vy, vz), dim=-1)
    quat = torch.zeros(n, 4, device=dev)
    quat[:, 0] = 1.0
    ang = torch.zeros(n, 3, device=dev)
    _write_ball_state(self._env, self._ball, env_ids, pos, quat, lin, ang)

  def _geometry(self, env_ids: torch.Tensor) -> BallSportGeometry:
    return resolve_pingpong_ball_sport_geometry(self._env, self.cfg).select(env_ids)

  def _sample_candidate(self, env_ids: torch.Tensor) -> TableTennisSample:
    geometry = self._geometry(env_ids)
    spawn_x_lo, spawn_x_hi = _resolve_x_range(
      geometry, self.cfg.spawn_x_range, self.cfg.spawn_x_range_mode
    )
    spawn_y_lo, spawn_y_hi = _resolve_y_range(
      geometry, self.cfg.spawn_y_range, self.cfg.spawn_y_range_mode
    )
    target_x_lo, target_x_hi = _resolve_x_range(
      geometry, self.cfg.target_x_range, self.cfg.target_x_range_mode
    )
    target_y_lo, target_y_hi = _resolve_y_range(
      geometry, self.cfg.target_y_range, self.cfg.target_y_range_mode
    )

    px = _uniform_between(spawn_x_lo, spawn_x_hi)
    py = _uniform_between(spawn_y_lo, spawn_y_hi)
    pz = geometry.bounce_z + self.cfg.spawn_z_offset
    tx = _uniform_between(target_x_lo, target_x_hi)
    ty = _uniform_between(target_y_lo, target_y_hi)

    vz_min, net_path_valid = _vz_min_for_net(
      px,
      tx,
      geometry,
      gravity=self.cfg.gravity,
      net_clearance=self.cfg.check.net_clearance,
    )
    vz = vz_min + torch.randn_like(vz_min).abs() * self.cfg.vz_std
    vx, vy, flight_t, valid_t = _solve_first_bounce_velocity(
      px,
      py,
      pz,
      tx,
      ty,
      vz,
      geometry,
      gravity=self.cfg.gravity,
    )
    sample = TableTennisSample(
      px=px,
      py=py,
      pz=pz,
      vx=vx,
      vy=vy,
      vz=vz,
      tx=tx,
      ty=ty,
      flight_t=flight_t,
      valid=net_path_valid & valid_t,
    )
    valid = check_candidate_trajectory(sample, geometry, self.cfg)
    return TableTennisSample(
      px=px,
      py=py,
      pz=pz,
      vx=vx,
      vy=vy,
      vz=vz,
      tx=tx,
      ty=ty,
      flight_t=flight_t,
      valid=valid,
    )

  def _fallback_candidate(self, env_ids: torch.Tensor) -> TableTennisSample:
    geometry = self._geometry(env_ids)
    spawn_x_lo, spawn_x_hi = _resolve_x_range(
      geometry, self.cfg.spawn_x_range, self.cfg.spawn_x_range_mode
    )
    spawn_y_lo, spawn_y_hi = _resolve_y_range(
      geometry, self.cfg.spawn_y_range, self.cfg.spawn_y_range_mode
    )
    target_x_lo, target_x_hi = _resolve_x_range(
      geometry, self.cfg.target_x_range, self.cfg.target_x_range_mode
    )
    target_y_lo, target_y_hi = _resolve_y_range(
      geometry, self.cfg.target_y_range, self.cfg.target_y_range_mode
    )
    px = 0.5 * (spawn_x_lo + spawn_x_hi)
    py = 0.5 * (spawn_y_lo + spawn_y_hi)
    pz = geometry.bounce_z + self.cfg.spawn_z_offset
    tx = 0.5 * (target_x_lo + target_x_hi)
    ty = 0.5 * (target_y_lo + target_y_hi)
    vz_min, net_path_valid = _vz_min_for_net(
      px,
      tx,
      geometry,
      gravity=self.cfg.gravity,
      net_clearance=self.cfg.check.net_clearance,
    )
    vz = torch.minimum(
      vz_min + max(self.cfg.vz_std, 0.2),
      torch.full_like(vz_min, self.cfg.vz_max),
    )
    vx, vy, flight_t, valid_t = _solve_first_bounce_velocity(
      px,
      py,
      pz,
      tx,
      ty,
      vz,
      geometry,
      gravity=self.cfg.gravity,
    )
    sample = TableTennisSample(
      px=px,
      py=py,
      pz=pz,
      vx=vx,
      vy=vy,
      vz=vz,
      tx=tx,
      ty=ty,
      flight_t=flight_t,
      valid=net_path_valid & valid_t,
    )
    valid = check_candidate_trajectory(sample, geometry, self.cfg)
    return TableTennisSample(
      px=px,
      py=py,
      pz=pz,
      vx=vx,
      vy=vy,
      vz=vz,
      tx=tx,
      ty=ty,
      flight_t=flight_t,
      valid=valid,
    )


def spawn_ball_from_provider(
  env: "ManagerBasedRlEnv",
  env_ids: torch.Tensor,
  *,
  provider_cfg: Any,
) -> None:
  """Event-manager wrapper for table-tennis feeders."""
  cache_key = f"_pingpong_ball_provider_{id(provider_cfg)}"
  provider: TableTennisFeeder | None = getattr(env, cache_key, None)
  if provider is None:
    provider = provider_cfg.build(env)
    setattr(env, cache_key, provider)
  provider.spawn(env_ids)


__all__ = [
  "TableTennisFeeder",
  "TableTennisFeederCfg",
  "TableTennisSample",
  "TrajectoryCheckCfg",
  "check_candidate_trajectory",
  "resolve_pingpong_ball_sport_geometry",
  "spawn_ball_from_provider",
]
